### ISSUE TITLE
Implement Hierarchical Clustering

### ISSUE THREAD

**Issue by DataFighter** [DistrictDataLabs/trinket#29]
We need to have some implementation of clustering that we can lose to build other features on . 

Hierarchical is useful because it is ideal for brushing, zooming, and filtering.

**Comment by rebeccabilbro** [comment]
Use agglomerative clustering in scikit-learn

**Comment by rebeccabilbro** [comment]
With the distance function, run general distance and optimize. Calculate minimum average distance or highest average distance, then use simulated annealing to find the optimal distance.
