### ISSUE TITLE
Enable user to include metadata with upload

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/trinket#44]
So that we have some sense of where the data is coming from.

**Comment by bbengfort** [comment]
Any thoughts on how we might go about this?

**Comment by rebeccabilbro** [comment]
At first, it could be a short text field with the URL to where the data came from or something. I guess we should make it optional.  Then, when you do the dataset preview, if there's a link, it would show up as something like "read more about this dataset..."

**Comment by bbengfort** [comment]
That's very doable. We might want to think about the entire workflow for uploading data; especially datasets that contain more than one file. Right now the uploader is just about tossing files at the server. If there is any other meta data you would like, toss it into this issue!

**Comment by bbengfort** [comment]
Make "dataset create form" similar to Github's "create repository" form. In advance of uploading files. Figure out the percent complete of the meta data information. 

- [ ] Create dataset form 
- [ ] Add LinkedIn profile % complete type widget
